### ISSUE TITLE
Is the bot coming back?

### ISSUE THREAD

**Issue by RippleBipple** [ecatherine13/Ultimate-Assistant-2#34]
I know the bot has been offline due to the creator's discord account being compromised but will the project ever come back and will the bot ever be online again? Or is it permanently shut down?

**Comment by ecatherine13** [comment]
It will go back up assuming discord support ever addresses the request. HOWEVER, it was recently announced that I will no longer be maintaining this project once discord's API changes go into effect beginning May 1st, 2022, so please keep that in mind. This code will be available for self-hosting but I will not be paying for bot hosting
